### ISSUE TITLE
Unable to add Providers Info

### ISSUE THREAD

**Issue by fab-rkd** [dukt/social#11]
### Description
I am using the Social 2.0.0-beta.10, with this i am not able to add providers.
I have added them in config/social.php file and also Trying to add them from Admin itself. But no luck.

All the `Social Settings > Settings(TAB)` are set to TRUE.
Social `Settings > Login Providers(TAB)`. This Shows no providers confgured.

I tried re-installing plugin via admin as well, but still the same issue.

### Steps to reproduce

1. Upgrade to 2.0.0-beta.10 via admin
2.  Try to save providers  `Settings >  Social >   Login Providers`

### Additional info

- Plugin version:  2.0.0-beta.10
- Craft version: Craft CMS 3.0.13.2
- PHP version: 7.0.30
- Database driver & version: MySQL 5.7.20
- Plugins & versions:

**Comment by emerico** [comment]
I am facing the same issue.

**Comment by benjamindavid** [comment]
The structure of the config array has changed a bit since beta 10, please make sure it's following that structure: https://docs.dukt.net/social/v2/configuration.html#loginproviders

There was also a bug in beta 10 where OAuth client ID and secret were not properly saved. This bug should be fixed in [beta 11](https://github.com/dukt/social/blob/master/CHANGELOG.md#200-beta11---2018-08-24)
