### ISSUE TITLE
Twitter login/register does not work anymore because of callback url

### ISSUE THREAD

**Issue by 24HOURSMEDIA** [dukt/social#30]
### Description

One cannot enter the supplied twitter redirect/callback in Twitter because '?' are not allowed anymore according to twitter.

### Steps to reproduce

1. Go to plugin settings page for twitter
2. Try to enter the redirect url into the twitter app, following the instructions

### Additional info

- Plugin version: 2.0.0
- Craft version: Craft Pro 3.1.15
- PHP version: 7.1.20
- Database driver & version:
- Plugins & versions:

**Comment by benjamindavid** [comment]
The plugin now shows a warning telling that Twitter doesn't accept callback URLs with query parameters anymore, and the docs have been updated:
https://docs.dukt.net/social/v2/twitter.html#oauth-configuration

Thanks for reporting!

**Comment by skoften** [comment]
Setting `usePathInfo` to `true` isn't a solution in our case, as we're using Nginx. `usePathInfo` seems to be a Apache only concept (https://github.com/craftcms/cms/issues/4287)

So my question is: what callback URL should we add to the Twitter app, because we're getting an invalid callback URL response when trying to connect via Twitter.

**Comment by bencroker** [comment]
Is there any update on using `usePathInfo` with Nginx?
